name: pr-dependabot-alerts
description:
  Workflow action that lets you know when a dependabot PR resolves a vuln
author: mdzhang

branding:
  icon: shield
  color: red

inputs:
  repo-token:
    description: 'The GitHub token used to read dependabot alerts'
    required: false
    default: ${{ github.token }}

outputs:
  dependabotAlertUrl:
    description:
      The link to the dependabot alert that the current PR fixes, if applicable
  vulnerabilitySeverityLevel:
    description: The severity of the vulnerability in the alert, if applicable

runs:
  using: node20
  main: dist/index.js
