---
name: security-alerts

on:
  pull_request:
    types:
      - opened

permissions:
  contents: read
  security-events: read

jobs:
  report-vulns:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]' && github.event_name == 'pull_request'
    steps:
      - name: Check if PR is vuln fix
        id: vuln-check
        uses: mdzhang/pr-dependabot-alerts@v0.0.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
